"""Initial migration

Revision ID: 4692689b044d
Revises:
Create Date: 2025-03-23 15:28:33.509147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel  # added

from sqlmodel import Text
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = "4692689b044d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config", postgresql.JSON(astext_type=Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inbound_trunks",
        sa.Column("trunk_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "livekit_sip_trunk_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("twilio_sid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "twilio_auth_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("sip_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sip_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("trunk_id"),
    )
    op.create_table(
        "knowledgebase",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("openai_file_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "openai_vector_store_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filesize", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outbound_trunks",
        sa.Column(
            "inbound_trunk_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "livekit_sip_trunk_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inbound_trunk_id"],
            ["inbound_trunks.trunk_id"],
        ),
        sa.PrimaryKeyConstraint("livekit_sip_trunk_id"),
    )
    op.create_table(
        "phone_numbers",
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trunk_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trunk_id"],
            ["inbound_trunks.trunk_id"],
        ),
        sa.PrimaryKeyConstraint("phone_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phone_numbers")
    op.drop_table("outbound_trunks")
    op.drop_table("knowledgebase")
    op.drop_table("inbound_trunks")
    op.drop_table("agents")
    # ### end Alembic commands ###
