"""add account id

Revision ID: e1e3dba5167b
Revises: 4692689b044d
Create Date: 2025-03-23 15:58:05.825578

"""
from typing import Sequence, Union
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlmodel import Text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e3dba5167b'
down_revision: Union[str, None] = '4692689b044d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebase', sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledgebase', 'account_id')
    # ### end Alembic commands ###
