"""initial migration

Revision ID: e5f9fe65b7c4
Revises:
Create Date: 2025-03-23 00:21:25.194793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "e5f9fe65b7c4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agents")
    op.drop_table("phone_numbers")
    op.drop_table("inbound_trunks")
    op.drop_table("knowledgebase")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledgebase",
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("openai_file_id", sa.VARCHAR(), nullable=False),
        sa.Column("filename", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inbound_trunks",
        sa.Column("trunk_id", sa.VARCHAR(), nullable=False),
        sa.Column("livekit_sip_trunk_id", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("trunk_id"),
    )
    op.create_table(
        "phone_numbers",
        sa.Column("phone_number", sa.VARCHAR(), nullable=False),
        sa.Column("trunk_id", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trunk_id"],
            ["inbound_trunks.trunk_id"],
        ),
        sa.PrimaryKeyConstraint("phone_number"),
    )
    op.create_table(
        "agents",
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("config", sqlite.JSON(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
